### ISSUE TITLE
follow-up: Sanitize health endpoint error details to prevent information disclosure

### ISSUE THREAD

**Issue by sabbour** [sabbour/kickstart#927]
# Follow-Up: Sanitize Health Endpoint Error Details

## Summary
The `/api/health` endpoint's 503 error response includes a raw `detail` field that exposes internal error information to unauthenticated callers. This includes filesystem paths (from module-not-found errors) and URL validation errors (from misconfigured endpoints).

## Root Cause
PR #924 added structured diagnostic error responses with `phase` and `hint` fields (good), but the `detail` field contains the raw error message passed directly from exception.message (see `packages/web/api/src/functions/health.ts` line 27).

**Example exposures:**
- Module error: `"Cannot find module '/home/user/kickstart/packages/pack-azure/dist/index.js'"`
- URL error: `"Invalid URL: https://abc-xyz-invalid-region.openai.azure.com/..."`

## Problem
- Filesystem paths leak internal server structure
- URL values expose endpoint configuration
- Unauthenticated endpoints should not expose implementation details

## Solution Options
1. **Drop the detail field entirely** — Rely on `phase` + `hint` only (safest, may lose debugging info)
2. **Sanitize the detail field** — Strip filesystem paths, truncate to 200 chars, generalize error messages
3. **Move detail to logs only** — Keep structured error for Application Insights, send only phase/hint to client

## Acceptance Criteria
- [ ] `detail` field is either removed from 503 response OR sanitized to remove:
  - Filesystem paths (replace with "<internal path>")
  - Full URLs (replace with "<configured endpoint>")
  - Internal module names
- [ ] Error messages remain helpful for debugging (via console logs, not public response)
- [ ] Health endpoint still returns diagnostic phase + hint for client-side error messages
- [ ] Related issue: #914 (LLM API endpoints error messaging)

## Security Classification
- **Severity:** Low (no credentials exposed, paths are relative to attacker-controlled setup, but still unnecessary)
- **Type:** Information Disclosure (minor)
- **CVSS:** ~2.7 (Low) — limited practical exploit path

## Context
- Introduced in PR #924 (Phase 1 diagnostic enhancements for #914)
- Identified by Zapp in security review
- Not blocking the PR merge, but tracked for future hardening
